# --- CONFIGURACIÓN BÁSICA ---
set -g status-bg "#1a1b26"
set -g status-fg "#a9b1d6"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

# --- PLUGINS ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-show-left-icon session

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'erikw/tmux-powerline'

# Open new panes/windows in the current path
bind v split-window -v -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# --- ATAJOS ESTILO VIM ---
# Moverse entre paneles con Alt + Flechas
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Modo copia corregido (estilo Vim real)
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Kill all panes except the current one
bind -r e kill-pane -a

run '~/.tmux/plugins/tpm/tpm'
