# --- CONFIGURACIÓN BÁSICA ---
# Unbind default
unbind C-b

# Set new prefix
set -g prefix C-Space

# Allow sending prefix to nested tmux sessions
bind C-Space send-prefix

# splits estilo Vim
bind h split-window -h   # izquierda/derecha
bind v split-window -v   # arriba/abajo

unbind '"'
unbind %

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'


set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

# --- PLUGINS ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @dracula-refresh-rate 5
set -g @dracula-border-contrast true
set -g @dracula-show-powerline true
set -g @dracula-transparent-powerline-bg true
# Etiquetas cortas
set -g @dracula-cpu-usage-label "CPU"
set -g @dracula-ram-usage-label "RAM"
set -g @dracula-battery-label "🦇 "
set -g @dracula-mac-player-play-icon "♪ "
set -g @dracula-mac-player-pause-icon "❚❚ "
set -g @dracula-kubernetes-context-label "⎈"
set -g @dracula-kubernetes-hide-user true        
set -g @dracula-kubernetes-eks-hide-arn true 

set -g @dracula-git-disable-status true
set -g @dracula-git-show-repo-name true
set -g @dracula-day-month true
set -g @dracula-show-location false
set -g @dracula-show-fahrenheit false
set -g @dracula-plugins "kubernetes-context cpu-usage ram-usage battery time"


set -g @dracula-cpu-usage-colors "dark_purple dark_gray"
set -g @dracula-ram-usage-colors "light_purple dark_gray"
set -g @dracula-battery-colors "dark_purple dark_gray"
set -g @dracula-time-colors "dark_purple dark_gray"
set -g @dracula-kubernetes-context-colors "light_purple dark_gray"
set -g @dracula-left-icon-colors "light_purple dark_gray"
# Configuración de Reloj (Solo Fecha corta, sin hora larga ni CEST)
set -g @dracula-time-format "%d/%m"
set -g @dracula-day-month true
set -g @dracula-military-time true

bind C-Up resize-pane -U 1
bind C-Down resize-pane -D 1
bind C-Left resize-pane -L 1
bind C-Right resize-pane -R 1

# Left Side
# Show my active session, window, pane name or id  
set-option -g status-left-length 50   # default 10



# Open new panes/windows in the current path
bind v split-window -v -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# --- ATAJOS ESTILO VIM ---
# Moverse entre paneles con Alt + Flechas
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Modo copia corregido (estilo Vim real)
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# don't rename windows automatically
set-option -g allow-rename off

# Kill all panes except the current one
bind -r e kill-pane -a

run '~/.tmux/plugins/tpm/tpm'
